services:
  mongo:
    image: mongo:${MONGO_VERSION:-5}
    # Start a single-node replica set (required for change streams and transactions)
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: mongod --replSet rs0
    ports:
      - '27017:27017'
