name: Pipeline

on: push

permissions:
  id-token: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20', '22', '24']
        mongodb-version: ['6', '7', '8']
        mongodb-package-version: ['6', '7']
    steps:
      - uses: actions/checkout@v4
      - run: MONGO_VERSION=${{ matrix.mongodb-version }} docker compose up -d
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: npm run lint
      - run: npm run format-check
      - run: npm install mongodb@${{ matrix.mongodb-package-version }} -D
      - run: npm run build
      - run: npm test
        env:
          CI: true
      - run: docker compose down
        if: always()
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: github.ref == 'refs/heads/main' && matrix.node-version == '24' && matrix.mongodb-version == '8' && matrix.mongodb-package-version == '7'
  publish:
    if: github.ref == 'refs/heads/main'
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: npm run build
      - run: npm publish || echo "Already published"
